#### 1. Write a program to generate an array of 30 numbers (1 to 30) of all possible shapes.

In [13]:
import numpy as n

In [26]:
g=n.random.randint(1,30,30)
g.reshape(5,6)
g.reshape(10,3)
g.reshape(3,10)

array([[28,  1, 14, 26,  6, 29,  4,  9,  3, 25],
       [29, 25, 26, 18, 29, 22, 14, 29,  9, 22],
       [ 6, 15,  4,  6, 23,  9,  8, 17, 12, 28]])

#### 2.Write a program to genrate an array of random integer numbers between 10 to 50 numbers of all possible shapes.

In [29]:
n.random.randint(10,50,9).reshape(3,3)

array([[11, 14, 14],
       [43, 27, 26],
       [46, 17, 24]])

#### 3. Write a program to generate an array of 100 equally spaced numbers between 1 to 7 numbers of possible shapes.

In [33]:
n.linspace(1,7,100,True)

array([1.        , 1.06060606, 1.12121212, 1.18181818, 1.24242424,
       1.3030303 , 1.36363636, 1.42424242, 1.48484848, 1.54545455,
       1.60606061, 1.66666667, 1.72727273, 1.78787879, 1.84848485,
       1.90909091, 1.96969697, 2.03030303, 2.09090909, 2.15151515,
       2.21212121, 2.27272727, 2.33333333, 2.39393939, 2.45454545,
       2.51515152, 2.57575758, 2.63636364, 2.6969697 , 2.75757576,
       2.81818182, 2.87878788, 2.93939394, 3.        , 3.06060606,
       3.12121212, 3.18181818, 3.24242424, 3.3030303 , 3.36363636,
       3.42424242, 3.48484848, 3.54545455, 3.60606061, 3.66666667,
       3.72727273, 3.78787879, 3.84848485, 3.90909091, 3.96969697,
       4.03030303, 4.09090909, 4.15151515, 4.21212121, 4.27272727,
       4.33333333, 4.39393939, 4.45454545, 4.51515152, 4.57575758,
       4.63636364, 4.6969697 , 4.75757576, 4.81818182, 4.87878788,
       4.93939394, 5.        , 5.06060606, 5.12121212, 5.18181818,
       5.24242424, 5.3030303 , 5.36363636, 5.42424242, 5.48484

#### 4. Write a program to filter out all the numbers (generated from que.3) which is greater than 3.84 and less than 6.57.

In [92]:
h=n.array([1,4,6,8])
h

array([1, 4, 6, 8])

In [107]:
g=h[h>3.56]  
gh=g[g<6.57]
gh
h

array([1, 4, 6, 8])

#### Write a program to replace first 3 numbers with 100 and middle 3'numbers with 200 and last 3 numbers with 300 in output of que.5

In [130]:
o=n.array(range(0,5))
o[0:3]=100
o[1:5]=200
o[2:]=300
o

array([100, 200, 300, 300, 300])

#### 6. Write a program to create a 5x5 matrix of random int numbers between 10 to 100 and

##### replace upper triangle with zeros and print as a new matrix

In [144]:
j=n.random.randint(10,100,25).reshape(5,5)
j

array([[23, 82, 26, 98, 14],
       [60, 25, 77, 48, 17],
       [21, 31, 80, 76, 24],
       [55, 46, 73, 68, 82],
       [39, 64, 17, 89, 28]])

In [145]:
c=0
for i in j:
    i[c+1:]="0"
    c=c+1
j    

array([[23,  0,  0,  0,  0],
       [60, 25,  0,  0,  0],
       [21, 31, 80,  0,  0],
       [55, 46, 73, 68,  0],
       [39, 64, 17, 89, 28]])

#### replace lower triangle with zeros and print as a new matrix

In [167]:
j=n.random.randint(10,100,25).reshape(5,5)
j

array([[90, 50, 74, 85, 54],
       [47, 68, 39, 19, 23],
       [26, 61, 88, 35, 58],
       [34, 49, 57, 96, 18],
       [48, 66, 51, 20, 14]])

In [168]:
c=1
for i in j:
    i[:c-1]=0
    c=c+1
j

array([[90, 50, 74, 85, 54],
       [ 0, 68, 39, 19, 23],
       [ 0,  0, 88, 35, 58],
       [ 0,  0,  0, 96, 18],
       [ 0,  0,  0,  0, 14]])