In [1]:
import numpy as ny
import matplotlib.pyplot as ml
import pandas as ps
import seaborn as sb
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.metrics import roc_auc_score,auc
from IPython.display import Image
from sklearn.tree import export_graphviz
from sklearn.metrics import roc_curve
from sklearn.model_selection import GridSearchCV


In [95]:
DF=ps.read_csv(r"C:\Users\ShinChan\Downloads\bank.csv")

In [3]:
DF.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
DF.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [5]:
DF.columns.unique()

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [6]:
PE=preprocessing.LabelEncoder()

In [7]:
def LE(df):
    for i in df.columns:
        df[i]=PE.fit_transform(df[i])
    return df

In [8]:
DS=LE(DF)

In [9]:
DS.tail()

age  job  marital  education  default  balance  housing  loan  contact  \
11157   15    1        2          0        0      425        1     0        0   
11158   21    7        1          1        0     1149        0     0        2   
11159   14    9        2          1        0      453        0     0        0   
11160   25    9        1          1        0      424        0     1        0   
11161   16    9        1          1        0      424        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  deposit  
11157   19      0       255         0      0         0         3        0  
11158   15      6        81         3      0         0         3        0  
11159   18      1       154         1      0         0         3        0  
11160    7      8         7         1    155         5         0        0  
11161    8      5       626         0      0         0         3        0

In [10]:
DS.select_dtypes(include="int64")

age  balance  day  duration  campaign  pdays  previous
0       41     2288    4      1021         0      0         0
1       38      469    4      1283         0      0         0
2       23     1618    4      1246         0      0         0
3       37     2356    4       577         0      0         0
4       36      608    4       671         1      0         0
...    ...      ...  ...       ...       ...    ...       ...
11157   15      425   19       255         0      0         0
11158   21     1149   15        81         3      0         0
11159   14      453   18       154         1      0         0
11160   25      424    7         7         1    155         5
11161   16      424    8       626         0      0         0

[11162 rows x 7 columns]

In [11]:
DS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null int32
marital      11162 non-null int32
education    11162 non-null int32
default      11162 non-null int32
balance      11162 non-null int64
housing      11162 non-null int32
loan         11162 non-null int32
contact      11162 non-null int32
day          11162 non-null int64
month        11162 non-null int32
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null int32
deposit      11162 non-null int32
dtypes: int32(10), int64(7)
memory usage: 1.0 MB


In [12]:
DS.isna().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [13]:
x=DS.drop(columns=["marital"],axis=1).values
y=DS.marital.values

In [14]:
x1,x2,y1,y2=train_test_split(x,y,test_size=0.3)

In [15]:
x1.shape

(7813, 16)

In [16]:
y1.shape

(7813,)

In [17]:
MM=DecisionTreeClassifier(max_depth=19,random_state=1)

In [18]:
MM.fit(x1,y1)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=19,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')

In [19]:
MM.score(x2,y2)

0.5700209017617199

In [20]:
MM.score(x1,y1)

0.9668501215922181

In [21]:
type(DS.marital.values)

numpy.ndarray

In [22]:
type(DS.drop(columns=["marital"],axis=1).values)

numpy.ndarray

In [23]:
ny.array(DS.drop(columns=["marital"],axis=1))

array([[41,  0,  1, ...,  0,  3,  1],
       [38,  0,  1, ...,  0,  3,  1],
       [23,  9,  1, ...,  0,  3,  1],
       ...,
       [14,  9,  1, ...,  0,  3,  0],
       [25,  9,  1, ...,  5,  0,  0],
       [16,  9,  1, ...,  0,  3,  0]], dtype=int64)

In [24]:
a,b,c,d=train_test_split(x,y,test_size=0.25)

In [25]:
MD=DecisionTreeClassifier().fit(a,c)

In [26]:
MD.predict_proba(b)[:,-1]

array([0., 0., 0., ..., 0., 1., 0.])

In [27]:
MD.predict(b)

array([1, 1, 1, ..., 1, 2, 1])

In [28]:
fp,tp,c=roc_curve(s,d)
auc(fp,tp)  

NameError: name 's' is not defined

In [ ]:
MD.predict(b)

In [ ]:
tp

In [ ]:
s

# DT - 2

In [29]:
DF.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   41    0        1          1        0     2288        1     0        2   
1   38    0        1          1        0      469        0     0        2   
2   23    9        1          1        0     1618        1     0        2   
3   37    7        1          1        0     2356        1     0        2   
4   36    0        1          2        0      608        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    4      8      1021         0      0         0         3        1  
1    4      8      1283         0      0         0         3        1  
2    4      8      1246         0      0         0         3        1  
3    4      8       577         0      0         0         3        1  
4    4      8       671         1      0         0         3        1

In [96]:
LC=preprocessing.LabelEncoder()
for i in DF.columns:
    DF[i]=LC.fit_transform(DF[i])

In [ ]:
DF.tail()

In [ ]:
DF.housing.value_counts()

In [97]:
y=ny.array(DF.housing)
x=ny.array(DF.drop(columns=["housing"],axis=1))

In [ ]:
DF.corr()

In [ ]:
DF.describe()

In [35]:
for i in DF.columns:
    DF[i]=DF[i].apply(lambda j:(j-DF[i].mean())/DF[i].std())
    

In [123]:
q,w,e,r=train_test_split(x,y,random_state=9,test_size=.3)
SM=DecisionTreeClassifier()

In [124]:
GS=GridSearchCV(SM,cv=10,n_jobs=3,param_grid=dix)
MMM=GS.fit(q,e)

In [125]:
dix={"criterion":["gini","entropy"],
                  "max_depth":[1,2,3],
                  "min_samples_split":[2,3]}

In [135]:
z=MMM.predict(w)
(z==r).sum()
MMM.

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=3,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]},


In [127]:
accuracy_score(r,z)

0.7079725291131681

In [78]:
ss=[("s","e"),1,2,3]
ss
ss.insert(2,5)
ss
bb="kart"
ko=[1,2,3]

In [ ]:
ml.plot(fp,tp)


In [ ]:
print(confusion_matrix(d,MD.predict(b)))

In [ ]:
accuracy_score(d,MD.predict(b))

# RanDom ForEst

In [ ]:
import time 
import random
import pandas as ps
import matplotlib.pyplot as ml
import numpy as ny
import seaborn as sb
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import confusion_matrix,classification_report,roc_auc_score,roc_curve,auc
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing

In [ ]:
df=ps.read_csv(r"C:\Users\ShinChan\Downloads\data (1).csv")

In [ ]:
df.isna().sum()

In [ ]:
df.tail()

In [ ]:
pl=preprocessing.LabelEncoder()
for i in df.columns:
    df[i]=pl.fit_transform(df[i])

In [ ]:
df.diagnosis.uniqueque()

In [ ]:
del df["Unnamed: 32"]

In [ ]:
x=df.drop(columns=["diagnosis"],axis=1).to_numpy()
y=df.diagnosis.to_numpy()

In [ ]:
type(y)

In [ ]:
w,x,y,z=train_test_split(x,y,test_size=.2,random_state=4)

In [ ]:
RFC=RandomForestClassifier()

In [ ]:
dis={"max_depth":[2,3,4],
    "criterion":["gini","entropy"],
    "bootstrap":[True,False],
    "max_features":["auto",'sqrt', 'log2', None]}

In [ ]:
cv=GridSearchCV(RFC,cv=10,param_grid=dis,n_jobs=3)

In [ ]:
cv

In [ ]:
cv.fit(w,y)

In [ ]:
cv.best_params_

In [ ]:
RFC.set_params(criterion = 'entropy',
                  max_features = 'auto', 
                  max_depth = 4)

In [ ]:
RFC.oob_score

In [ ]:
cv.predict(x.reshape(1,-1))